name: Lizard Analysis
on: [push, pull_request]

jobs:
  lizard-api:
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "./src"
      EXCLUDE_PATH: "\"./node_modules/*\"" 

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - run: "pip install lizard jinja2"

      - run: "mkdir lizard-reports"
      
      - run: "lizard -o lizard-reports/lizard-analysis-raw.csv -a 7 -x ${{env.EXCLUDE_PATH}} ${{env.SCAN_PATH}}"
      - run: "lizard -o lizard-reports/lizard-analysis-duplicate.md -Eduplicate -a 7 -x ${{env.EXCLUDE_PATH}} ${{env.SCAN_PATH}}"
      - run: "lizard -H -o lizard-reports/lizard-analysis-report.html -a 7 -x ${{env.EXCLUDE_PATH}} ${{env.SCAN_PATH}}"
      
      # adding column names to csv report for later analysis
      - run: sed -i '1s/^/NLOC,CNN,token,PARAM,length,location,file,functionName,FullFunctionName,from,to\n/' lizard-reports/lizard-analysis-raw.csv

      - name: Archive lizard reports
        uses: actions/upload-artifact@v3
        with:
          name: "lizard_reports_API"
          path: "./lizard-reports/"
